export {default as Home} from './Home/Home.jsx';
export {default as Product} from './Product/Product.jsx';
export {default as Products} from './Products/Products.jsx';
export {default as Navbar} from './Navbar/Navbar.jsx';
export {default as Footer} from './Footer/Footer.jsx';
export {default as Slider} from './Slider/Slider.jsx';
export {default as FeaturedProducts} from './FeaturedProducts/FeaturedProducts.jsx'
export {default as Card} from './Card/Card.jsx';
export {default as Categories} from './Categories/Categories.jsx';
export {default as Contact} from './Contact/Contact.jsx';
