export {default as Home} from './Home/Home.jsx';
export {default as Product} from './Product/Product.jsx';
export {default as Products} from './Products/Products.jsx';
export {default as Navbar} from './Navbar/Navbar.jsx';
export {default as Footer} from './Footer/Footer.jsx';
export {default as Slider} from './Slider/Slider.jsx';
export {default as FeaturedProducts} from './FeaturedProducts/FeaturedProducts.jsx'
export {default as Card} from './Card/Card.jsx';
export {default as List} from './List/List.jsx';
export {default as Cart} from './Cart/Cart.jsx';
export {default as Loading} from './Loading/Loading.jsx'
export {default as More} from './More/More.jsx'
export {default as Error} from './Error/Error.jsx'
